"""Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms."""

#Empty list for fibonaccy numbers
f=[]
#Set first elements to not get out of list range while looping and to
#not have if checks during whole loops as these ifs only matter for 
#first 2 elements 
f=[0,1]


for i in range(2,401):
    #adding previous two numbers together 
    e=f[i-1]+f[i-2]
    #put sum of elements in fibonacci list
    f.append(e)

#New list for fibonacci less than <4000000
f_less=[i for i in f if i<=4000000]    

f_even=[i for i in f_less if i%2==0]
    
#sum(f_even) adds up all list elements one by one    
print("The even fibonaccis smaller than 4 Million are "+str(f_even),"and their sum is "+str(sum(f_even)))

